# This workflow will install the optional workflow dependencies from pyproject.toml and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    # Install Python dependencies from pyproject.toml using the 'workflow' optional dependencies
    - name: Install workflow dependencies from pyproject.toml
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
        # Install the workflow-specific dependencies
        hatch run pip install .[workflow]

    # Run tests with pytest
    - name: Test with pytest
      run: |
        hatch run pytest tests